version: "3.8"

services:
  terraquery-api:
    build:
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - terraquery-net

  terraquery-ui:
    build:
      dockerfile: UI_Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - terraquery-api
    networks:
      - terraquery-net

networks:
  terraquery-net:
    driver: bridge